service: realworld

provider:
  name: aws
  runtime: nodejs10.x
  region: eu-west-1
  environment:
    DYNAMODB_NAMESPACE: ${opt:stage, "dev"}
    WATCHTOWER_EVENT_KINESIS_STREAM:
      Ref: EventsStream
    # DEBUG_WATCHTOWER: 1
    PROFILE_WATCHTOWER: 1
    WT_RW_PROP_COUNT: ${env:WT_RW_PROP_COUNT}
  iamRoleStatements:
    - Effect: Allow             # Required for writing wt events
      Action:
        - 'kinesis:DescribeStream'
        - 'kinesis:PutRecord'
        - 'kinesis:PutRecords'
      Resource:
        Fn::GetAtt: [EventsStream, Arn]
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/*"

custom:
  # handlerFilePostfix: '-wrapper'
  handlerFilePostfix: ${env:WT_RUN_NO_RECORDING, '-wrapper'}

package:
  exclude:
    - test/**
    - coverage/**
    - lambda-node-logo.png
    - .nyc_output/**

plugins:
  - serverless-dynamodb-local
  - serverless-offline
  - serverless-step-functions

functions:

  ## Users API
  createUser:
    handler: src/User${self:custom.handlerFilePostfix}.create
    events:
      - http:
          method: POST
          path: /api/users
          cors: true
    role:
      'Fn::GetAtt': [ EventsStreamWriter, Arn ]


  loginUser:
    handler: src/User${self:custom.handlerFilePostfix}.login
    events:
      - http:
          method: POST
          path: /api/users/login
          cors: true
    role:
      'Fn::GetAtt': [ EventsStreamWriter, Arn ]


  getUser:
    handler: src/User${self:custom.handlerFilePostfix}.get
    events:
      - http:
          method: GET
          path: /api/user
          cors: true
    role:
      'Fn::GetAtt': [ EventsStreamWriter, Arn ]


  updateUser:
    handler: src/User${self:custom.handlerFilePostfix}.update
    events:
      - http:
          method: PUT
          path: /api/user
          cors: true
    role:
      'Fn::GetAtt': [ EventsStreamWriter, Arn ]


  getProfile:
    handler: src/User${self:custom.handlerFilePostfix}.getProfile
    events:
      - http:
          method: GET
          path: /api/profiles/{username}
          cors: true
    role:
      'Fn::GetAtt': [ EventsStreamWriter, Arn ]

  followUser:
    handler: src/User${self:custom.handlerFilePostfix}.follow
    events:
      - http:
          method: POST
          path: /api/profiles/{username}/follow
          cors: true
    role:
      'Fn::GetAtt': [ EventsStreamWriter, Arn ]

  unfollowUser:
    handler: src/User${self:custom.handlerFilePostfix}.follow
    events:
      - http:
          method: DELETE
          path: /api/profiles/{username}/follow
          cors: true
    role:
      'Fn::GetAtt': [ EventsStreamWriter, Arn ]

  ## Articles API
  createArticle:
    handler: src/Article${self:custom.handlerFilePostfix}.create
    events:
      - http:
          method: POST
          path: /api/articles
          cors: true
    role:
      'Fn::GetAtt': [ EventsStreamWriter, Arn ]

  getArticle:
    handler: src/Article${self:custom.handlerFilePostfix}.get
    events:
      - http:
          method: GET
          path: /api/articles/{slug}
          cors: true
    role:
      'Fn::GetAtt': [ EventsStreamWriter, Arn ]

  udpateArticle:
    handler: src/Article${self:custom.handlerFilePostfix}.update
    events:
      - http:
          method: PUT
          path: /api/articles/{slug}
          cors: true
    role:
      'Fn::GetAtt': [ EventsStreamWriter, Arn ]

  deleteArticle:
    handler: src/Article${self:custom.handlerFilePostfix}.delete
    events:
      - http:
          method: DELETE
          path: /api/articles/{slug}
          cors: true
    role:
      'Fn::GetAtt': [ EventsStreamWriter, Arn ]

  favoriteArticle:
    handler: src/Article${self:custom.handlerFilePostfix}.favorite
    events:
      - http:
          method: POST
          path: /api/articles/{slug}/favorite
          cors: true
    role:
      'Fn::GetAtt': [ EventsStreamWriter, Arn ]

  unfavoriteArticle:
    handler: src/Article${self:custom.handlerFilePostfix}.favorite
    events:
      - http:
          method: DELETE
          path: /api/articles/{slug}/favorite
          cors: true
    role:
      'Fn::GetAtt': [ EventsStreamWriter, Arn ]

  listArticles:
    handler: src/Article${self:custom.handlerFilePostfix}.list
    events:
      - http:
          method: GET
          path: /api/articles
          cors: true
    role:
      'Fn::GetAtt': [ EventsStreamWriter, Arn ]

  getArticlesFeed:
    handler: src/Article${self:custom.handlerFilePostfix}.getFeed
    events:
      - http:
          method: GET
          path: /api/articles/feed
          cors: true
    role:
      'Fn::GetAtt': [ EventsStreamWriter, Arn ]

  getTags:
    handler: src/Article${self:custom.handlerFilePostfix}.getTags
    events:
      - http:
          method: GET
          path: /api/tags
          cors: true
    role:
      'Fn::GetAtt': [ EventsStreamWriter, Arn ]

  ## Comments API
  createComment:
    handler: src/Comment${self:custom.handlerFilePostfix}.create
    events:
      - http:
          method: POST
          path: /api/articles/{slug}/comments
          cors: true
    role:
      'Fn::GetAtt': [ EventsStreamWriter, Arn ]

  getComments:
    handler: src/Comment${self:custom.handlerFilePostfix}.get
    events:
      - http:
          method: GET
          path: /api/articles/{slug}/comments
          cors: true
    role:
      'Fn::GetAtt': [ EventsStreamWriter, Arn ]

  deleteComment:
    handler: src/Comment${self:custom.handlerFilePostfix}.delete
    events:
      - http:
          method: DELETE
          path: /api/articles/{slug}/comments/{id}
          cors: true
    role:
      'Fn::GetAtt': [ EventsStreamWriter, Arn ]

  ## Utils API
  ping:
    handler: src/Util${self:custom.handlerFilePostfix}.ping
    events:
      - http:
          method: GET
          path: /api/ping
          cors: true
    role:
      'Fn::GetAtt': [ EventsStreamWriter, Arn ]

  purgeData:
    handler: src/Util${self:custom.handlerFilePostfix}.purgeData
    events:
      - http: DELETE /api/__TESTUTILS__/purge
    role:
      'Fn::GetAtt': [ EventsStreamWriter, Arn ]

  ## GDPR Consent API
  consent:
    handler: src/GDPR${self:custom.handlerFilePostfix}.consent
    events:
      - http:
          method: POST
          path: /api/consent
          cors: true
    role:
      'Fn::GetAtt': [ EventsStreamWriter, Arn ]

  revoke:
    handler: src/GDPR${self:custom.handlerFilePostfix}.revoke
    events:
      - http:
          method: DELETE
          path: /api/consent
          cors: true
    role:
      'Fn::GetAtt': [ EventsStreamWriter, Arn ]

  ########################################
  ## Watchtower Functions
  ##
  ##   Log Ingestion
  watchtower-ingestion: ${file(watchtower/functions.yml):watchtower-ingestion}   # Event ingestion function
  watchtower-monitor:   ${file(watchtower/functions.yml):watchtower-monitor}     # Event monitor
  wt-monitor-trigger:   ${file(watchtower/functions.yml):wt-monitor-trigger}     # A function that triggers the event monitoring step-functions state machine



  ##########################################
  ## Watchtower Checker State Machine
  ##

stepFunctions:
  stateMachines:
    checker: ${file(watchtower/stateMachine.yml):stateMachines.checker}

  ##
  ## End of Watchtower Checker State Machine
  ##########################################


resources:
  Outputs:
    WTCheckerMachine: ${file(watchtower/outputs.yml):Outputs.WTCheckerMachine}
    WTEventsKinesisStream: ${file(watchtower/outputs.yml):Outputs.WTEventsKinesisStream}
    WTEventsKinesisStreamARN: ${file(watchtower/outputs.yml):Outputs.WTEventsKinesisStreamARN}

  Resources:
    UsersDynamoDBTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          -
            AttributeName: username
            AttributeType: S
          -
            AttributeName: email
            AttributeType: S
        KeySchema:
          -
            AttributeName: username
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: realworld-${self:provider.environment.DYNAMODB_NAMESPACE}-users
        GlobalSecondaryIndexes:
          -
            IndexName: email
            KeySchema:
              -
                AttributeName: email
                KeyType: HASH
            Projection:
              ProjectionType: ALL

    ArticlesDynamoDBTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          -
            AttributeName: slug
            AttributeType: S
          -
            AttributeName: dummy
            AttributeType: S
          -
            AttributeName: updatedAt
            AttributeType: N
        KeySchema:
          -
            AttributeName: slug
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: realworld-${self:provider.environment.DYNAMODB_NAMESPACE}-articles
        GlobalSecondaryIndexes:
          -
            IndexName: updatedAt
            KeySchema:
              -
                AttributeName: dummy
                KeyType: HASH
              -
                AttributeName: updatedAt
                KeyType: RANGE
            Projection:
              ProjectionType: ALL

    CommentsDynamoDBTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
          -
            AttributeName: slug
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: realworld-${self:provider.environment.DYNAMODB_NAMESPACE}-comments
        GlobalSecondaryIndexes:
          -
            IndexName: article
            KeySchema:
              -
                AttributeName: slug
                KeyType: HASH
            Projection:
              ProjectionType: ALL

    GDPRConsentDynamoDBTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          -
            AttributeName: uuid
            AttributeType: S
        KeySchema:
          -
            AttributeName: uuid
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: realworld-${self:provider.environment.DYNAMODB_NAMESPACE}-gdpr-consent

    ########################################
    ## Watchtower Resources
    ##

    EventsTable:          ${file(watchtower/ddbTables.yml):Resources.EventsTable}
    CheckpointsTable:     ${file(watchtower/ddbTables.yml):Resources.CheckpointsTable}
    InvocationStream:     ${file(watchtower/kinesisStreams.yml):Resources.InvocationStream}
    EventsStream:         ${file(watchtower/kinesisStreams.yml):Resources.EventsStream}
    EventWriterRole:      ${file(watchtower/iamRoles.yml):Resources.EventWriterRole}
    EventReaderRole:      ${file(watchtower/iamRoles.yml):Resources.EventReaderRole}
    StateMachineListExec: ${file(watchtower/iamRoles.yml):Resources.StateMachineListExec}

    ##
    ## END of Watchtower Resources
    ########################################
